name: Create release

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        type: boolean
        default: false
        description: "Dry run: setting this to `true` will skip the final step of publishing the release, leaving it as a draft-release. This can be helpful for testing and debugging. Note that the tag and release are still getting generated and the next run of this result in incremented release version. To avoid this, do not forget to delete the resulting release and tag."

jobs:
  gen-version:
    name: Generate semantic version from branch and tags
    uses: kyma-project/eventing-tools/.github/workflows/get-version-from-release-branch-reusable.yml@d491378dbbeef63bf8616f1a1b2b1a49ea5f9eeb
    # outputs: VERSION

  bump-sec-scanners-config:
    name: Bump the sec-scanners-config.yaml
    needs: gen-version
    uses: kyma-project/eventing-tools/.github/workflows/bump-sec-scanners-config-reusable.yml@e8d1cd652dd636ad14b420da984f0bd4bf84ee0a
    with:
      VERSION: ${{ needs.gen-version.outputs.VERSION }}
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}

  run-unit-test:
    name: Run Unit Tests
    needs: [gen-version, bump-sec-scanners-config]
    uses: kyma-project/eventing-tools/.github/workflows/unit-test-reusable.yml@d491378dbbeef63bf8616f1a1b2b1a49ea5f9eeb

  run-golint-cli:
    name: Run Golint-cli
    needs: [gen-version, bump-sec-scanners-config]
    uses: kyma-project/eventing-tools/.github/workflows/lint-reusable.yml@d491378dbbeef63bf8616f1a1b2b1a49ea5f9eeb

  build-image:
    name: Build image
    needs: [gen-version, run-unit-test, run-golint-cli]
    uses: kyma-project/eventing-tools/.github/workflows/trigger-prow-build-job-reusable.yml@f509756e135aa2255cfd9e96c833fe5c6e511b3b
    with:
      VERSION: ${{ needs.gen-version.outputs.VERSION }}
      TIMEOUT: 120000 # 20 minutes
      INTERVAL: 6000 # 1 minute
      CONTEXT: "release-eventing-manager-build"
      COMMIT_REF: ${{ github.ref_name }}
    secrets: inherit

  create-draft-release:
    name: Create a draft release
    needs: [gen-version, run-unit-test, run-golint-cli, build-image]
    uses: kyma-project/eventing-tools/.github/workflows/create-draft-release-reusable.yml@5c713986ad2249557ad12481a3608480f548975c
    with:
      VERSION: ${{ needs.gen-version.outputs.VERSION }}
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  render-and-upload-manifest:
    name: Render and upload the manifests
    needs: [gen-version, create-draft-release, build-image]
    uses: kyma-project/eventing-tools/.github/workflows/render-and-upload-manifests-reusable.yml@d491378dbbeef63bf8616f1a1b2b1a49ea5f9eeb
    with:
      VERSION: ${{ needs.gen-version.outputs.VERSION }}
      CR_FILE: eventing-default-cr.yaml
      CRD_FILE: eventing-manager.yaml
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}

  publish-release:
    if: ${{ !inputs.DRY_RUN }}
    needs: [gen-version, render-and-upload-manifest, build-image]
    name: Publish the release
    uses: kyma-project/eventing-tools/.github/workflows/publish-release-reusable.yml@d491378dbbeef63bf8616f1a1b2b1a49ea5f9eeb
    with:
      VERSION: ${{ needs.gen-version.outputs.VERSION }}
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}
